### ISSUE TITLE
How to get space_guid on Cloud Foundry platform

### ISSUE THREAD

**Issue by michaellihs** [spring-cloud/spring-cloud-open-service-broker#102]
Recently `CreateServiceInstanceRequest.getSpaceGuid()` is marked deprecated.

When I try to access the `spaceGuid` via `CreateServiceInstanceRequest.getContext().getProperty("space_guid")` it returns `null` for an object which serializes to the following JSON:

```` json
{
  "platform_instance_id": null,
  "api_info_location": "api.our.cloud.foundry.com/v2/info",
  "originating_identity": null,
  "async_accepted": true,
  "parameters": {
    "index_prefix": "jenkins-build-92",
    "retention_period": 120
  },
  "context": {
    "platform": "cloudfoundry",
    "platform": "cloudfoundry",
    "organization_guid": "34c45fca-fa37-4c62-bc64-6082c65b4e87",
    "space_guid": "ccc85d22-7819-4023-99c6-acd85d8e5dc9"
  },
  "plan_id": "index-plan",
  "organization_guid": "34c45fca-fa37-4c62-bc64-6082c65b4e87",
  "space_guid": "ccc85d22-7819-4023-99c6-acd85d8e5dc9",
  "service_instance_id": "808ab800-33c4-406d-84de-9ebc40867a5c",
  "service_definition": null,
  "service_id": "service-id"
}
````

So basically my question is: which is the non-deprecated way to get the `spaceGuid` from a `CreateServiceInstanceRequest` object?

Besides, when writing integration tests that use the `CreateServiceInstanceRequest`, I couldn't figure out a way to create an object with context type `CloudFoundryContext` besides de-serializing it from JSON, since all constructors etc. are private.

**Comment by royclarkson** [comment]
See @scottfrederick's [answer](https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/101#issuecomment-401086972), on issue #101 for info on the context.

**Comment by scottfrederick** [comment]
> So basically my question is: which is the non-deprecated way to get the spaceGuid from a CreateServiceInstanceRequest object?

The intended design was to validate the type of the context and then get platform-specific fields - something like this: 

```
Context context = createServiceInstanceRequest.getContext();
if (context.getPlatform().equals(CLOUD_FOUNDRY_PLATFORM)) {
    CloudFoundryContext cloudFoundryContext = (CloudFoundryContext) context;
    String spaceGuid = cloudFoundryContext.getSpaceGuid();
}
```

That's admittedly a bit unwieldy, and casting is not ideal, but the thinking was that you'd verify the concrete `Context` type before trying to get platform-specific fields from it. 

> When I try to access the spaceGuid via `CreateServiceInstanceRequest.getContext().getProperty("space_guid")` it returns `null`

I see why that's happening, and I think you should be able to get the property that way if you prefer. We'll work on a fix for that. 

> Besides, when writing integration tests that use the CreateServiceInstanceRequest, I couldn't figure out a way to create an object with context type CloudFoundryContext

This is obviously something users need to do in tests (since this issue and #101 both mention it). We can also look at adding builders for the concrete `Context` subtypes to make this easier.

**Comment by royclarkson** [comment]
Resolved in #104

**Comment by royclarkson** [comment]
@michaellihs do you have an opinion on the solution in #104? We can consider a release soon if it resolves your concerns.

**Comment by michaellihs** [comment]
Hi @royclarkson - after updating to `2.0.1.RELEASE` the `space_guid` can be accessed via `CreateServiceInstanceRequest.getContext().getProperty("spaceGuid")` - thanks a lot for your assistance!

**Comment by royclarkson** [comment]
@michaellihs thanks. feedback is always appreciated!
