### ISSUE TITLE
Deserialization issue for spring classes that have been migrated to the builder pattern (no constructor)

### ISSUE THREAD

**Issue by vivinjoseph9** [spring-cloud/spring-cloud-open-service-broker#110]
hi all,

I am getting the below error:

```
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.springframework.cloud.servicebroker.model.catalog.Catalog]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.cloud.servicebroker.model.catalog.Catalog` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 1, column: 2]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:238)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:223)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:100)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:991)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:974)
....
....
..
```

        ResponseEntity<Catalog> response = basicAuthRestTemplate.exchange(getUrl(XBEPaths.SB_CATALOG_PATH), HttpMethod.GET, null,
        		Catalog.class);

AND

        ResponseEntity<CreateServiceInstanceResponse> response = basicAuthRestTemplate.exchange(url, HttpMethod.PUT, entity,
                CreateServiceInstanceResponse.class);

for the above call in my test, the call is successful and the reponse is obtained, then this response is deserialized from json to java. that is where the error is thrown 

	private Object readJavaType(JavaType javaType, HttpInputMessage inputMessage) throws IOException {
		try {
			if (inputMessage instanceof MappingJacksonInputMessage) {
				Class<?> deserializationView = ((MappingJacksonInputMessage) inputMessage).getDeserializationView();
				if (deserializationView != null) {
					return this.objectMapper.readerWithView(deserializationView).forType(javaType).
							readValue(inputMessage.getBody());
				}
			}
			return this.objectMapper.readValue(inputMessage.getBody(), javaType);
		}
		catch (InvalidDefinitionException ex) {
			throw new HttpMessageConversionException("Type definition error: " + ex.getType(), ex);
		}
		catch (JsonProcessingException ex) {
			throw new HttpMessageNotReadableException("JSON parse error: " + ex.getOriginalMessage(), ex);
		}
	} 

Previously this used to work because the classes given in the expected response type(Catalog - package org.springframework.cloud.servicebroker.model.catalog;
, CreateServiceInstanceResponse - package org.springframework.cloud.servicebroker.model.instance;
 etc) had default constructors, however after the migration to the builder pattern the rest call throws a type definition error, due to the lack of a default constructor which it is looking for.

I tried migrating to the latest jackson version, to see if that could resolve the issue , but it dint help. This problem is specific to the classes that have migrated to the builder pattern. 

Please do let me know if anyone has come across this , or atleast has a workaround for this problem.

Thanks in advance.

Vivin.

**Comment by royclarkson** [comment]
Thanks for the feedback. We actually ran into a similar issue internally when needing to support configuration properties for a [catalog](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web/Catalog.java) and the other objects needed for marshaling. So now we have two versions of those objects that serve two different purposes. We'll discuss how to handle this better. Our goal isn't to prevent people from doing testing of their apps.

**Comment by vivinjoseph9** [comment]
@royclarkson Thank you for your reply.  Is there any update on how to handle this ?

**Comment by arghya88** [comment]
I ran into same error. How do we resolve this?

**Comment by royclarkson** [comment]
I'm considering adding default public constructors for the model objects. I'll see how this works and follow up.

**Comment by IvaDonchev** [comment]
Hello, when we could have a released version with this fix?

**Comment by royclarkson** [comment]
It's available in the 2.1.0.M1 milestone now, and will be eventually released in 2.1.0.RELEASE. I'll update the release dates on github.

**Comment by manolvalchev** [comment]
@royclarkson, could you please share more details in terms of timeline? I could not find the the release dates on github, you pointed above. Thanks in advance!

**Comment by royclarkson** [comment]
Yeah, I haven't updated them yet, but will do that today. I think we're about ready to push out 2.1.0.M2, so that may go out this week. Then we'll have an RC before the final GA release.

**Comment by IvaDonchev** [comment]
Hi @royclarkson is there any update on the new release?

**Comment by royclarkson** [comment]
2.1.0.M2 is available now, however the deserialization fix was already available in 2.1.0.M1. We're still working toward the GA release.

**Comment by IvaDonchev** [comment]
Hi @royclarkson, I have tested the fix and it works for me, however I need the GA release in order to consume it. Please, let me know when it is planned to be released as we are depending on this change and it blocks our release as well. Thank you in advance.

**Comment by IvaDonchev** [comment]
Hi @royclarkson, any update on when the new GA release is coming?

**Comment by manolvalchev** [comment]
@royclarkson, Is there any way to speed up the release process? I could not find any entry in the [Spring Calendar](http://spring-calendar.cfapps.io) for the GA release. A while ago, there was but now it's gone.

**Comment by IvaDonchev** [comment]
Hi @royclarkson, you said that it will be shortly released 20 days ago and still I don't see a release: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-open-service-broker-core
Please, take this with higher priority. We are waiting for this release more than 2 months.
Thanks!

**Comment by manolvalchev** [comment]
@royclarkson, @scottfrederick, sorry for bothering you but could you please explain the reason for the delay of the release? Is there any way that we, as stakeholders, could help in speeding up? It's already becoming really weird from my PoV as consumer and dependent of the library. It makes me thinking of alternative solution of my problem but it should rather work the other way around.

**Comment by royclarkson** [comment]
@IvaDonchev @manolvalchev thanks for your patience. We've had other priorities in related projects, and there haven't been any additional changes to this codebase since the last release. I'm working on getting two changes in today. After that, I'll push out an RC1 release. I'll let you know when it's available for testing. I plan to push the GA on Friday.

**Comment by royclarkson** [comment]
Finishing an issue. RC1 didn't go out today, but will Wednesday. GA still for Friday.

**Comment by IvaDonchev** [comment]
Hi @royclarkson, when should we expect the GA release today? It will then be published in the maven repository: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-open-service-broker, right?
I could see that there is already a pre-release: https://github.com/spring-cloud/spring-cloud-open-service-broker/releases/tag/v2.1.0.RC1 however it is again in the milestone repository which doesn't work for me.

**Comment by royclarkson** [comment]
@IvaDonchev @manolvalchev 2.1.0.RELEASE is out and available in maven central. https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-starter-open-service-broker-webmvc/2.1.0.RELEASE/pom

**Comment by manolvalchev** [comment]
@royclarkson, thanks a lot!

**Comment by MaoJianwei** [comment]
I got this problem too, and adding default constructor works. With spring-web-5.0.8-RELEASE

**Comment by NikolayVaklinov10** [comment]
Easy fix. I just change the Java version to Java 16 and it works
