### ISSUE TITLE
unbind-service exception:  Required String parameter 'service_id' is not present

### ISSUE THREAD

**Issue by allanfelipesilva** [spring-cloud/spring-cloud-open-service-broker#114]
Hi, I am using cloud foundry in SAP canary landscape.
After the upgrade for open-service-broker my service broker is getting an error during **unbind-service** operation:
MissingServletRequestParameterException: Required String parameter 'service_id' is not present

I changed the method ServiceInstanceBindingController#deleteServiceInstanceBinding to have optional parameters: service_id and plan_id and now everything is workind again on cloud foundry service.

I can fork and submit the changes, but do you know why those are mandatory parameters for deletion but not mandatory for other operations ?

Class: ServiceInstanceBindingController.java
Method: deleteServiceInstanceBinding
```java
public ResponseEntity<String> deleteServiceInstanceBinding(
			@PathVariable Map<String, String> pathVariables,
			@PathVariable(ServiceBrokerRequest.INSTANCE_ID_PATH_VARIABLE) String serviceInstanceId,
			@PathVariable(ServiceBrokerRequest.BINDING_ID_PATH_VARIABLE) String bindingId,
			@RequestParam(value = ServiceBrokerRequest.SERVICE_ID_PARAMETER, required = false) String serviceDefinitionId,
			@RequestParam(value = ServiceBrokerRequest.PLAN_ID_PARAMETER, required = false) String planId,
			@RequestHeader(value = ServiceBrokerRequest.API_INFO_LOCATION_HEADER, required = false) String apiInfoLocation,
			@RequestHeader(value = ServiceBrokerRequest.ORIGINATING_IDENTITY_HEADER, required = false) String originatingIdentityString) {

```

I believe this is similar to [issue 53](https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/53)

thank you and best regards,
Allan

**Comment by scottfrederick** [comment]
@allanfelipesilva According to the [Open Service Broker API spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#unbinding), the `service_id` and `plan_id` are required parameters on an unbinding request: 


Query-String Field | Type | Description
-- | -- | --
service_id* | string | MUST be the ID of the service associated with the binding being deleted.
plan_id* | string | MUST be the ID of the plan associated with the binding being deleted.

`* Query parameters with an asterisk are REQUIRED.`

As far as I can tell, these parameters have been required parameters in the spec for a long time. The Spring Cloud - Cloud Foundry Service Broker 1.x also required these parameters on the `deleteServiceInstanceBinding` request. 

Are you getting the `MissingServletRequestParameterException: Required String parameter 'service_id' is not present` error in a test, or when the service broker is actually getting called by a client (e.g. Cloud Controller)?

**Comment by allanfelipesilva** [comment]
HI I am getting when called from cloud controller, on tests everything is fine.

**Comment by royclarkson** [comment]
Out of curiosity, what version of CloudFoundry are you running?

**Comment by allanfelipesilva** [comment]
hi
api version:    2.115.0

**Comment by scottfrederick** [comment]
@allanfelipesilva In the request `DELETE //v2/service_instances//service_bindings/?plan_id=<myplan_id>&service_id=<myservice_id>`, the `//` in the URL are curious. 

The first `//` at the beginning does appear to be related to what was reported in #53, and would be caused by the way the way the broker is being registered with CC. Can you share the `cf` command used to register the service broker? 

There should be a service instance ID path element between `service_instances` and `service_bindings` in the URL, as well as a service binding ID after `service_bindings` (as in `/v2/service_instances/:instance_id/service_bindings/:binding_id?plan_id=<myplan_id>&service_id=<myservice_id>`). Are the `:instance_id` and `:binding_id` elements of the path really missing from the URL passed by CC?

**Comment by allanfelipesilva** [comment]
hi, 
I just hide here the actual values of the parameters, but I have all the values orgid, bindingid, plan_id, service_id  in the URL correctly.

the only thing I dont have is the  CF ID in the begging, the URL starts with  "//v2/service_instances/"
I had to change the websecurity config to allow non normalized URLs.

This broker was created originally in version 1.0.1 of spring service broker, maybe thats the issue, I should recreate it.

I dont have the command to register the service broker now, I am just able to push new version.  but tomorrow I can get the command and comment here.

**Comment by allanfelipesilva** [comment]
Hi, now everything is correct using 2.0.0 release,
I created in a different space the service broker and it was the same issue from #53 .

command:
`cf create-service-broker myservice-test user somethingpassword https://myservice-test.cfapps.com/mycfid --space-scoped
`

now I created with a suffix in the url "mycfid" in a test space, the unbind and deletion are working fine with version 2.0.0.

the url begins with:
"DELETE /**mycfid**/v2/service_instances/"

and everything is working, 
thank you for your help , I will cancel the pull request.

Thank you for your project and hard work

best regards,
Allan Silva
