### ISSUE TITLE
`@ConditionalOnProperty` target property with no metadata

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-open-service-broker#119]
Several auto-configurations use a condition on a property that has no metadata. As a result, trying to use it to customize the auto-configuration lead to a warning in an IDE.

The report detected the following:

```
org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration [spring.cloud.openservicebroker.apiVersionCheckEnabled]
org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration#serviceBrokerApiVersionProperty [spring.cloud.openservicebroker.apiVersion]
org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerAutoConfiguration#catalog [spring.cloud.openservicebroker.catalog.services[0].id]
```

Please note that properties in `@ConditionalOnProperty` must use the canonical format (so `spring.cloud.openservicebroker.apiVersionCheckEnabled` must be `spring.cloud.openservicebroker.api-version-check-enabled`).

**Comment by AlbertoImpl** [comment]
Thank you @snicoll for letting us know!
I am working on adding the `additional-spring-configuration-metadata.json` and updating it to use the canonical format and I can see the property appearing on the IDE.
Is there any way for us to realise when are we missing the metadata apart from manually checking each one of them?

Thanks!

**Comment by snicoll** [comment]
@AlbertoImpl thanks for the feedback. That report was generated by Jetbrains using a tool they use to optimize IntelliJ IDEA. I think the intent is to add this as of 2018.3. Perhaps @yanncebron can point us to a bit more details as how we could invoke that ourselves?

**Comment by YannCebron** [comment]
Please install 2018.3 EAP available from https://www.jetbrains.com/idea/nextversion/

Invoke `Help->Edit Custom Properties` and add `idea.is.internal=true`, restart IDE.

In project with Spring Boot open main class, then invoke `Help->Find Action` , search and invoke `Spring Boot Diagnostics` and a report will be created

**Comment by AlbertoImpl** [comment]
Great addition @YannCebron! It will be very useful for us.

Although, I am not sure if I did something wrong here: https://github.com/AlbertoImpl/spring-cloud-open-service-broker/commit/eeeb3a97c9b25d627acb1456bcfea4c75fe1605e
or if there is something wrong with intelliJ:
I am getting: 
![screen shot 2018-09-19 at 15 27 16](https://user-images.githubusercontent.com/405869/45756267-c2531400-bc20-11e8-800d-d7d68ff1f52d.png)

Also, the diagnostics reports the key missing:
```
@ConditionalOnProperty w/ unresolved config key(s): (5)
.....
org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration [spring.cloud.openservicebroker.api-version-check-enabled]
org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerAutoConfiguration#catalog [spring.cloud.openservicebroker.catalog.services[0].id]
```

We have the `configuration-processor` https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-autoconfigure/build.gradle#L37
and the `compileJava.dependsOn(processResources)` https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-autoconfigure/build.gradle#L51

And in a project that uses that library I can see the values:
![screen shot 2018-09-19 at 15 47 33](https://user-images.githubusercontent.com/405869/45757351-6a69dc80-bc23-11e8-854a-a1570db1f1f8.png)

And the report doesn't display that key missing:
```
@ConditionalOnProperty w/ unresolved config key(s): (11)
....
org.springframework.cloud.appbroker.autoconfigure.CloudFoundryClientAutoConfiguration#tokenProvider [spring.cloud.appbroker.deployer.cloudfoundry.username|spring.cloud.appbroker.deployer.cloudfoundry.password]
org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerAutoConfiguration#catalog [spring.cloud.openservicebroker.catalog.services[0].id]
```

Shouldn't we be getting the same output in the parent project as in the children for those keys?

Thanks a lot!

**Comment by YannCebron** [comment]
Thanks for your feedback:

1) Warning about missing annotation processor is a bug in Gradle support for `annotationProcessor` scope, see https://youtrack.jetbrains.com/issue/IDEA-187868

2) `@ConditionalOnProperty w/ unresolved config key(s)` will only show unresolved keys used directly on `@ConditionalOnProperty` annotation in code

I'm not sure I understand the last sentence about project/children projects?

**Comment by AlbertoImpl** [comment]
Thanks again @YannCebron! 
Let me try to explain myself better.

I have a project `p1` that defines a key `k1` using `@ConditionalOnProperty`.
If I add  `k1` to `additional-spring-configuration-metadata.json` I would expect not to see it under `@ConditionalOnProperty w/ unresolved config key(s)`.
However, I am seeing it as per:
```
@ConditionalOnProperty w/ unresolved config key(s): (5)
.....
org.springframework.cloud.servicebroker.autoconfigure.web.ApiVersionWebMvcAutoConfiguration [spring.cloud.openservicebroker.api-version-check-enabled]
org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerAutoConfiguration#catalog [spring.cloud.openservicebroker.catalog.services[0].id]
``` 

Also, If I have a project `p2` that uses `p1` where I can not see `k1` under `@ConditionalOnProperty w/ unresolved config key(s)`.
```
@ConditionalOnProperty w/ unresolved config key(s): (11)
....
org.springframework.cloud.appbroker.autoconfigure.CloudFoundryClientAutoConfiguration#tokenProvider [spring.cloud.appbroker.deployer.cloudfoundry.username|spring.cloud.appbroker.deployer.cloudfoundry.password]
org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerAutoConfiguration#catalog [spring.cloud.openservicebroker.catalog.services[0].id]
```

What is confusing to me is that it is behaving as it should when autocompleting `k1` on `p2` and also the report is fine on `p2` but when running it on `p1` I can see `k1` under `@ConditionalOnProperty w/ unresolved config key(s)` when it shouldn't.

**Comment by YannCebron** [comment]
My first guess would be that generated metadata in `p1` is probably not picked up from the compiler output due to `annotationProcessor` scope issue above (generated metadata is "local" to `p1` yet).

**Comment by AlbertoImpl** [comment]
That is an excellent guess. 
I will be waiting for the issue above to be fixed and provide more feedback if I find any problems. Thanks a lot @YannCebron!
