### ISSUE TITLE
Missing plan_updateable property for Service Plan

### ISSUE THREAD

**Issue by zoharyehezkely** [spring-cloud/spring-cloud-open-service-broker#139]
Hi,

According to the 2.14 spec:
https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md
plan_updateable property was added to Plan.

It seems that this property is not implemented in any of the versions published here:
https://spring.io/projects/spring-cloud-open-service-broker

Can you please verify?

**Comment by zoharyehezkely** [comment]
Hi Alberto,

You are right.
I was mistakenly looking at the master docs:
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md

What confused me the notice under: 
Changes Since v2.13
Clarified that the plan_updateable field affects modifying the Service Plan, not parameters (PR)

In v2.14 it is indeed not implemented.

Thanks,
Zohar.

**Comment by AlbertoImpl** [comment]
No worries at all Zohar, glad it helped!

Regards,
Alberto
