### ISSUE TITLE
[Maven] Wrong dependency scope

### ISSUE THREAD

**Issue by loganmzz** [spring-cloud/spring-cloud-open-service-broker#148]
Version: 2.1.0.RELEASE

**Problem:**
From POM of `spring-cloud-starter-open-service-broker-webmvc` and `spring-cloud-open-service-broker-autoconfigure` have most important dependencies marked as runtime scope meaning by default, `spring-boot-starter-web` and `spring-cloud-open-service-broker-core` are not available at compile/code time.

**Expectation:**
Please fix POMs or documentation.

**Workaround:**

Adds following to `pom.xml`:

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-open-service-broker-autoconfigure</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-open-service-broker-core</artifactId>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

**Comment by royclarkson** [comment]
@loganmzz this should be fixed in the latest `2.1.1.BUILD-SNAPSHOT`. Disregard my previous comment about the optional web dependency. In 2.x, the `spring-cloud-starter-open-service-broker-webmvc` starter should (and now does) pull that in.
