### ISSUE TITLE
Missing catalog plan.plan_updateable support

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-open-service-broker#152]
Ability to set [Plan.plan_updateable](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-plan-object) in the catalog does not seem available in 2.X branch in [Plan.java](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/1d11768d85cadde705a8a2508b4c98cc3fe42f0e/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web/Plan.java#L35).

**Comment by royclarkson** [comment]
That field (and a few other new ones) has yet to be released as part of the spec. v2.14 does not include them. 

https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#plan-object
