### ISSUE TITLE
Typo in Maven Artifact ID on Releases Page

### ISSUE THREAD

**Issue by forbushbl** [spring-cloud/spring-cloud-open-service-broker#158]
It appears on the releases page, the Artifact ID is
> `<artifactId>spring-cloud-starter-open-service-broker-`**webmc**`</artifactId>`

But it should be
> `<artifactId>spring-cloud-starter-open-service-broker-`**webmvc**`</artifactId>`

**Comment by scottfrederick** [comment]
@forbushbl I think I got them all. Thanks!
