### ISSUE TITLE
Improve support for `metadata.imageUrl` in configuration properties

### ISSUE THREAD

**Issue by aegershman** [spring-cloud/spring-cloud-open-service-broker#207]
I realize this is minor, and to be entirely honest I even researched whether this is part of the OSB spec, but:

Is there a way to include an image which will be used by a service broker in a marketplace? 

e.g., PCF's marketplace shows a blank white image for the broker:

<img width="611" alt="Screen Shot 2019-05-14 at 8 54 46 PM" src="https://user-images.githubusercontent.com/5619476/57743441-b4a83e00-768a-11e9-8107-c38ee36fbec8.png">

Not a biggie. Just curious if there's way it could be included as a b64 encoded text string or something.

Thanks for your time!

**Comment by royclarkson** [comment]
We can add this. We already have a few CF specific metadata, so it's not a stretch to include this as well. Thanks for the suggestion.

**Comment by aegershman** [comment]
Ah I think I see now: 

https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata you can add "`metadata.imageUrl`" as a key/value entry in the service `metadata` Map.

So two thoughts:
- Since it's looking for a URL, I guess you couldn't do a b64 encoding of the image. Not a biggie.
- Since it's exposed through the metadata object, I suppose this is technically already possible.

Thanks for your time, I appreciate it. Feel free to close this whenever, or I can close it soon 👍

**Comment by scottfrederick** [comment]
@aegershman 

> Since it's exposed through the metadata object, I suppose this is technically already possible.

That's correct, as you can see in [this example](https://github.com/spring-cloud-samples/bookstore-service-broker/blob/master/src/main/java/org/springframework/cloud/sample/bookstore/servicebroker/config/ServiceCatalogConfiguration.java#L43-L45) where similar fields are set in `metadata`. 

> Since it's looking for a URL, I guess you couldn't do a b64 encoding of the image.

Even though the OSBAPI spec calls the field `imageUrl`, Cloud Foundry supports setting the value of this key in the `metadata` map to a base64-encoded string. That should be more clear in the spec, but I suppose that behavior is platform-dependent.

**Comment by aegershman** [comment]
Oh! Well if that's the case, then yeah, that'd be great. Thanks for clarifying that 👍

**Comment by royclarkson** [comment]
I was thinking we could make the metadata model objects a bit easier to work with. I might try to experiment.
