### ISSUE TITLE
Incorrect response codes for fetching non-existant instance/binding

### ISSUE THREAD

**Issue by ilyavy** [spring-cloud/spring-cloud-open-service-broker#211]
Hello!

There is a little issue with the conformance to *OpenServiceBroker API specification v2.14*.
While fetching a service instance if the service instance with the specified id does not exist, [service broker must return](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-instance) `404 Not Found`, however, now it returns `422 Unprocessable Entity`.
The similar situation with [fetching a service binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-binding) (must return `404` as well), but now returns `500 Internal Server Error`.

**Comment by ilyavy** [comment]
This PR #212 should close the issue

**Comment by royclarkson** [comment]
Closed in #212
