### ISSUE TITLE
Incorrect a response code for fetching service bindings with nonexistent serviceInstance

### ISSUE THREAD

**Issue by aukhatov** [spring-cloud/spring-cloud-open-service-broker#223]
Hi @royclarkson @scottfrederick !!!

There is an issue with the conformance to [spec OSB API](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-binding).
While fetching a **service bindings** if the **service instance** with the **specified id does not exist**, service broker must return `404 Not Found`.  Because if service instance doesn't exist therefore service bindings also don't exist.

However when I try to fetch like this: 
`/v2/service_instances/<doesnot-exist-service-id>/service_bindings/<doesnot-exist-binding-id>`
I get an incorrect code `422 Unprocessable Entity`.

**Comment by royclarkson** [comment]
@aukhatov I haven't looked at it yet, but does this apply to the 3.0.2 release that was published yesterday? thanks!

**Comment by aukhatov** [comment]
@royclarkson It doesn't apply to the 3.0.2 release. The bug was even before v3.0.x

**Comment by royclarkson** [comment]
@aukhatov thanks for clarifying
