### ISSUE TITLE
Catalog definition at /v2/catalog returns always json object instead of array

### ISSUE THREAD

**Issue by pchrzasz** [spring-cloud/spring-cloud-open-service-broker#240]
The OSB spec at [link](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#catalog-management) specifies that under level `services.metadata` entries which are complex are not json object but json arrays. Example for features and licenses:
`
 "metadata": {
        "displayName": "Displayed Name",
        "serviceType": "application",
        "author": "None",
        "version": "1.0.0",
        "licenses": [
          "Lic1",
          "Lic2"
        ],
        "features": [
          "Hosting",
          "Scaling",
        }
`

But after defining in application.yaml cataloge definition:
`
metadata:
              displayName: 'Displayed Name'
              serviceType: 'application'
              author: 'None'
              version: '1.0.0'
              licenses:
                - 'Lic1'
                - 'Lic2'
              features:
                - 'Hosting'
                - 'Scaling'
`
enpdoint `/v2/catalog` returns:

`
"metadata": {
...
        "licenses": {
          "0": "Lic1",
          "1": "Lic2"
        },
        "features": {
          "0": "Hosting",
          "1": "Scaling"
        }
...
      }
`

but should
`
"metadata": {
...
        "licenses": ["Lic1", "Lic2"],
        "features": ["Hosting", "Scaling"]
....
      }
`

What I already found out is that yaml with something like:
`
features:
    - 'Hosting'
    - 'Scaling'
`
is read as a map, not as an array. 

Similar issue was already created but for 'services.plan.metadata', not for 'services.metadata': https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/155

**Comment by royclarkson** [comment]
Thanks for reporting!

**Comment by royclarkson** [comment]
We actually do have a [`ServiceMetadata`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web/ServiceMetadata.java) that is available in the latest 3.1.x milestone and snapshots, but it hasn't been released as GA yet. I'm not sure that addresses your issue though. Maybe we can reuse some of the code that was added in #161. Specifically, several of the helper methods in [`MethodSchema`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/3.0.x/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web/MethodSchema.java) for converting properties to arrays.

**Comment by pchrzasz** [comment]
Currently I used workaround for this:
`
ServiceDefinition serviceDefinition = 
ServiceDefinition.builder().metadata("features", Arrays.asList("Hosting", "Scaling"))
`

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-autoconfigure/src/main/java/org/springframework/cloud/servicebroker/autoconfigure/web/ServiceMetadata.java would be helpful ofc, but I wanted to define catalog inside yaml file.

Yes, probably solution from https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/161 would help.
