### ISSUE TITLE
Security Issue in commons-beanutils 1.9.3

### ISSUE THREAD

**Issue by RaghavPrakash** [spring-cloud/spring-cloud-open-service-broker#242]
spring-cloud-open-service-broker-core has a direct dependency on commons-beanutils 1.9.3. There is a new vulnerability with CVSS score 7.5 [here](http://mail-archives.apache.org/mod_mbox/www-announce/201908.mbox/%3cC628798F-315D-4428-8CB1-4ED1ECC958E4@apache.org%3e).

Our open source vulnerability tool has been reporting this issue for the last couple of weeks.

The mitigation involves migrating to 1.9.4. Will this be taken up?

**Comment by royclarkson** [comment]
@RaghavPrakash thanks for reporting! We'll update the dependency and push out a release asap.

**Comment by RaghavPrakash** [comment]
@royclarkson , we're using spring-cloud-starter-open-service-broker-webmvc. The latest version available is 2.1.2.RELEASE and it still transitively contains commons-beanutils 1.9.3. Any plans to patch the 2.1.X series?

**Comment by royclarkson** [comment]
@RaghavPrakash Curious, is there a reason not to migrate to the latest release? Regardless, I'll create a 2.1.3 patch release with updated dependencies. Thanks for the feedback!
