### ISSUE TITLE
Please confirm compatibility with Spring Boot 2.2

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-open-service-broker#245]
We're heading towards an RC1 of Spring Boot 2.2 soon, followed [by GA in Q4](https://github.com/spring-projects/spring-boot/milestones). Can you please confirm full compatibility of the starter with Spring Boot 2.2?

As soon as we hear from you, we can enable the starter again on start.spring.io, see https://github.com/spring-io/start.spring.io/issues/266

Thanks!

**Comment by royclarkson** [comment]
We have a nightly integration build that checks compatibility with the latest boot and framework snapshots. https://build.spring.io/browse/CLOUD-SCOSBI

**Comment by snicoll** [comment]
Great, I've enabled the entry again in https://github.com/spring-io/start.spring.io/commit/35eda7d3892341fbd8b8f20585dbf1fe216f0def
