### ISSUE TITLE
ServiceInstanceBindingDoesNotExistException extends RuntimeException and not ServiceBrokerException

### ISSUE THREAD

**Issue by skodupuganti** [spring-cloud/spring-cloud-open-service-broker#257]
I have stumbled upon this case where only the ServiceInstanceBindingDoesNotExistException in package  org.springframework.cloud.servicebroker.exception does not extend the ServiceBrokerException. Is this intended for any purpose, if not we should change it to be in line with other exceptions so as to have one base exception to handle.

**Comment by royclarkson** [comment]
Thanks for reporting. Yes, it should extend `ServiceBrokerException` to be consistent with the others.
