### ISSUE TITLE
ServiceBrokerInvalidParametersException should return HTTP 400

### ISSUE THREAD

**Issue by fang10** [spring-cloud/spring-cloud-open-service-broker#262]
I noticed this file [ServiceBrokerBadRequestException](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/1.0.x/src/main/java/org/springframework/cloud/servicebroker/exception/ServiceBrokerBadRequestException.java) was introduced in version 1.x, but it became missing since version 2.x.

What's the reason to drop it?

or should we change [ServiceBrokerInvalidParametersException](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/exception/ServiceBrokerInvalidParametersException.java) to return 400?

**Comment by royclarkson** [comment]
The entire project was refactored for version 2. I don't remember why we dropped or changed that exception. Can you provide more information with a scenario or use case that describes the issue you are having? For more information, all of the exceptions and their return values can be seen in the [`ServiceBrokerExceptionHandler`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java). Thanks.

**Comment by fang10** [comment]
Thanks for the info. The reason I asked about it is that we have a need to check for invalid parameter for provision instance request. According to the osb spec https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#provisioning, it should return 400 bad request if parameters are not valid in the context of service broker.

We can't do it because there is no such exception exists in the library

**Comment by royclarkson** [comment]
After reviewing the spec, I believe `ServiceBrokerInvalidParametersException` should be returning a 400, although I wonder if it shouldn't be renamed too. We already have a `ServiceBrokerAsyncRequiredException` that returns a 422. But we're also missing an exception for the `MaintenanceInfoConflict` error code that should also return 422. I'll add another issue for that.

**Comment by royclarkson** [comment]
This is related to #215. You can see there are a few exceptions that the framework throws in relation to invalid parameters that will return a 400. Maybe we still have a gap where the implementing application wants to be able to throw an exception.
