### ISSUE TITLE
Can the library provide a way to write a custom OSB exception

### ISSUE THREAD

**Issue by fang10** [spring-cloud/spring-cloud-open-service-broker#264]
We want to return 403 forbidden for permission error, the library does not have a predefined exception for it. Is it possible to provide library user a way to write a custom exception with desired http error code?

**Comment by royclarkson** [comment]
You should be able to do this without any additional functionality added to this project. Create a class similar to [`ServiceBrokerWebMvcExceptionHandler`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerWebMvcExceptionHandler.java). Give your exception handler class a higher priority order so it takes precedence over the provided one. Add it to the context and your custom exceptions will be handled. See the `@ControllerAdvice` JavaDoc for more info.

**Comment by fang10** [comment]
Thanks, that is definitely helpful
