### ISSUE TITLE
Service broker exceptions and response status codes

### ISSUE THREAD

**Issue by mateusz-stefanski** [spring-cloud/spring-cloud-open-service-broker#279]
I will start with an example. [Open Service Broker API specification](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md) requires one of the following status codes to be returned when a [service instance is fetched](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#fetching-a-service-instance):
- 422 if the instance is being updated
- 404 if the instance doesn't exist or is being provisioned
- 200 otherwise

Now let's see what [Spring Cloud Open Service Broker Java docs](https://docs.spring.io/spring-cloud-open-service-broker/docs/3.1.0.RELEASE/apidocs/org/springframework/cloud/servicebroker/service/ServiceInstanceService.html#getServiceInstance-org.springframework.cloud.servicebroker.model.instance.GetServiceInstanceRequest-) tell us:

> Throws:
ServiceInstanceDoesNotExistException - if a service instance with the given ID is not known to the broker
ServiceBrokerOperationInProgressException - if a an operation is in progress for the service instance

Going further, it turns out that throwing [ServiceInstanceDoesNotExistException](https://docs.spring.io/spring-cloud-open-service-broker/docs/3.1.0.RELEASE/apidocs/org/springframework/cloud/servicebroker/exception/ServiceInstanceDoesNotExistException.html)

> will result in an HTTP status code 422 UNPROCESSABLE ENTITY being returned to the platform

And throwing [ServiceBrokerOperationInProgressException](https://docs.spring.io/spring-cloud-open-service-broker/docs/3.1.0.RELEASE/apidocs/org/springframework/cloud/servicebroker/exception/ServiceBrokerOperationInProgressException.html)

> will result in an HTTP status code 404 NOT FOUND being returned to the platform

If you look at other service instance operations defined in [OSBA spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md) and compare it with corresponding [Spring Cloud Open Service Broker docs](https://docs.spring.io/spring-cloud-open-service-broker/docs/3.1.0.RELEASE/apidocs/org/springframework/cloud/servicebroker/service/ServiceInstanceService.html), you will find more such inconsistencies.

**Comment by royclarkson** [comment]
Thanks for the feedback. `ServiceInstanceDoesNotExistException` is overloaded and the java doc should be updated to reflect that. If you look at the controller, you can see that for `getServiceInstance` it's actually [returning a `404 HTTP NOT FOUND` for a `ServiceInstanceDoesNotExistException`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L191). However, for `deleteServiceInstance` it [returns a GONE status](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L302). And the default status returned in the exception handler is [HTTP 422](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java#L98)

Looking at the spec for fetching a service instance, it states:

> 404 Not Found - MUST be returned if the Service Instance does not exist or if a provisioning operation is still in progress.

`ServiceBrokerOperationInProgressException` should be used for the "or if a provisioning operation is still in progress" scenario. As such, [it also returns a 404 HTTP NOT FOUND](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java#L170).

> 422 Unprocessable Entity - MUST be returned if the Service Instance is being updated and therefore cannot be fetched at this time. The response body MUST contain error code "ConcurrencyError"

This scenario may be handled by the [` ServiceBrokerConcurrencyException`](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceBrokerExceptionHandler.java#L230)
