### ISSUE TITLE
Unable to throw 409 Conflict Https status

### ISSUE THREAD

**Issue by harshalb007** [spring-cloud/spring-cloud-open-service-broker#285]
Hello team,
I am implementing the service broker using Spring.

I have provided an implementation class for ServiceInstanceBindingService.
In this, according to the OSBAPI specification given [here](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#api-overview)
If someone provides already existing bindingId but with different attributes, we should throw 409 status.
But I am unable to find a way to achieve this.
Will you please help me out.

Thanks.

**Comment by royclarkson** [comment]
Hi, thanks for the question. You may throw a [ServiceInstanceBindingExistsException](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/exception/ServiceInstanceBindingExistsException.java) for this case. Similarly, there is a [ServiceInstanceExistsException](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/exception/ServiceInstanceExistsException.java) for when an service instance doesn't exist. I believe this answers the question, so I'm closing the issue. If you disagree, please reopen and we'll continue the discussion.
