### ISSUE TITLE
maintenance_info is missing from CSIReq, USIReq and error code exception

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-open-service-broker#290]
## Expected behavior

As a service broker author, 
* In order to respond to `cf update-service --upgrade` requests, 
* I need to receive `MaintenanceInfo` in update service instance request (along with previousValue)
* In order to respond to invalid OSB CSI request with invalid maintenance_info
--upgrade` requests, 
* I need to receive `MaintenanceInfo` in create service instance request

## Current behavior

MaintenanceInfo is only available in the plan object

### Background:

Maintenance-info was added in 2.15 spec version see https://github.com/openservicebrokerapi/servicebroker/pull/642/files but poorly documented in [release notes](https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md) as merely

> Added maintenance info support to Service Plans.

#233 and #239 only covered the service plan part, but missed the CSIR,UPSIR and exception

**Comment by royclarkson** [comment]
@gberche-orange fyi, I'll back port this change into a `3.1.2.RELEASE` soon, since it's a fix for OSBAPI 2.15 compatibility.
