### ISSUE TITLE
Why is bindingId globally unique and not unique per instance

### ISSUE THREAD

**Issue by harshalb007** [spring-cloud/spring-cloud-open-service-broker#292]
What is the problem?
Trying to understand the purpose of bindingId

Who does this affect?
Affects the development of service broker we are developing

Do you have any proposed solutions?
Binding Id should be unique per instance

Additional context
We are developing Service broker as per OSBAPI standards.
While implementing create binding endpoint we found that as per OSBAPI specification, "binding_id MUST be a globally unique non-empty string. This ID will be used for future unbind requests, so the Service Broker will use it to correlate the resource it creates."

According to our understanding, bindingId gives access to the instance for which the binding request is made. Then why is that OSBAPI suggests to have the bindingId Globally Unique.??

**Comment by royclarkson** [comment]
In terms of a service broker, a binding represents the unique association of an app and a service instance. A service instance may be bound to multiple apps, and each of those associations would have a unique binding ID. For example, if you have two apps and each app is bound to a mysql service instance, each of those bindings would have a unique binding ID. Hope that helps.

https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#types-of-binding

**Comment by mheath** [comment]
Regardless, the bindingId is provided by the platform so if the bindingId is unique per service instance or unique globally, it won't make any difference for the service broker. The service broker still has to use the bindingId it was given.
