### ISSUE TITLE
Could not find class [org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration]

### ISSUE THREAD

**Issue by elch78** [spring-cloud/spring-cloud-open-service-broker#293]
Hi, I tried to modularize an application and ran into this exception

    Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:335)
	at org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:446)

After some debugging I found that it might be caused by the dependency on Spring Cloud serviceBroker.

I reproduced the Problem with a demo project: https://github.com/elch78/ServiceBrokerWebMvcAutonconfigClassNotFound.git

It's just a package with two classes, a SpringBootConfiguration and a test. Running the Test or the application triggers the exception.

**Comment by elch78** [comment]
I tried to find the cause by myself but had no luck.

"org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration" was moved to another package with Spring Boot 2.

From debugging I also found that the exception probably is caused by some @AutoConfigureAfter annotation with a hardcoded classname.

**Comment by royclarkson** [comment]
@elch78 Thanks for the interest in the project. I see your sample project is using the original version 1.0 project dependency. I recommend that you use the latest release available. The name of the dependency has changed, as seen in the maven coordinates below. Please see the project README for a version compatibility matrix and the [reference documentation](https://docs.spring.io/spring-cloud-open-service-broker/docs/current/reference/html5/#getting-started) for more information about getting started.

```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-open-service-broker</artifactId>
  <version>3.1.1.RELEASE</version>
</dependency>
```

**Comment by elch78** [comment]
@royclarkson thanks! It is a legacy project that had that dependency. I Didn't see that there are newer versions available.
