### ISSUE TITLE
Add a Catalog builder class.

### ISSUE THREAD

**Issue by mheath** [spring-cloud/spring-cloud-open-service-broker#3]
Creating a `Catalog` is kind of painful and results in some ugly code, i.e. https://github.com/spring-cloud-samples/cloudfoundry-service-broker/blob/master/src%2Fmain%2Fjava%2Forg%2Fspringframework%2Fcloud%2Fservicebroker%2Fmongodb%2Fconfig%2FCatalogConfig.java

We should provide a builder that makes this easier.

**Comment by scottfrederick** [comment]
Fixed in c56080e5ec8ed97ba8fe4e15ac2031073fbc45ae
