### ISSUE TITLE
Service instance labeling 

### ISSUE THREAD

**Issue by andreaAlkalay** [spring-cloud/spring-cloud-open-service-broker#311]
Hi,

In OSB 2.16 Spec version an option to label service instances was added.

I would like to request to add the support in this specific feature and contribute the relevant changes.

Information on the labeling option:
https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v216
https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#service-instance-metadata

Thanks,
Andrea.

**Comment by andreaAlkalay** [comment]
Hi @royclarkson 
I have the code ready in a local branch.
How do I get permissions to push it and create a PR?
Thanks,
Andrea.

**Comment by royclarkson** [comment]
Hi Andrea, thanks for following up. Have you forked the project in GitHub? If not, [create a fork in your own GitHub account](https://guides.github.com/activities/forking/). Then you can push your local branch to your fork. After that you can create a new pull request from this project page using your fork and branch. If this is your first time going through the process, there are many resources available to help. Here's one GitHub guide that walks you through the process:

https://guides.github.com/activities/forking/

**Comment by andreaAlkalay** [comment]
Hi @royclarkson,
PR is ready - https://github.com/spring-cloud/spring-cloud-open-service-broker/pull/313.

I see the coverage check failed, not sure why..
Thanks,
Andrea.

**Comment by royclarkson** [comment]
@andreaAlkalay thanks! You can ignore the coverage check. It doesn't prevent us from merging the PR.
