### ISSUE TITLE
bad documentation link

### ISSUE THREAD

**Issue by nhomble** [spring-cloud/spring-cloud-open-service-broker#317]
In the readme, there is a link for the [reference documentation](https://docs.spring.io/spring-cloud-open-service-broker/docs/current/reference/html5/) but this leads to a 404. If I drop `html5/` then I arrive at the recent `3.3.0` docs

**Comment by royclarkson** [comment]
Thanks for reporting! Are you interested in submitting a PR to fix the link?

**Comment by nhomble** [comment]
np I can create one later today

**Comment by royclarkson** [comment]
Closed in b14c9e60670227a7e02de60c57fdbaa69151bf6a
