### ISSUE TITLE
Support OSB API 2.16

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-open-service-broker#318]
Release notes: https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v216

- [x] Add guidance for remembering the state of service instance and service binding operations (no code changes required)
- [x] Add guidance to handle 500 errors from Service Instance update (no code changes required)
- [x] Add guidance to handle requests with invalid data (no code changes required)
- [x] #353 
- [x] Specify that Platforms SHOULD NOT reuse IDs (no code changes required)
- [x] #287 
- [x] #365 
- [x] #372 
- [x] Clarify the response code when Platform does not provide the required API version header (this project offers a `ServiceBrokerApiVersionMissingException`, which results in an HTTP 400 response as indicated in the clarified spec)
- [x] #311 
- [x] #335

**Comment by kamalsethiya** [comment]
@royclarkson - could you please suggest the timeline to enable support for OSBv2.16 with latest version of Spring Boot 2.7.x. I can see in the [readme](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/main/README.adoc) that its under development. Thanks

**Comment by StefanREbertsch** [comment]
We would need this feature for a Siemens project. So we would be very interested for an update, ...

**Comment by royclarkson** [comment]
@kamalsethiya @StefanREbertsch are there OSB 2.16 features that you need that are currently not supported within the current release? Many of the outstanding items here are guidance and don't require code changes.

**Comment by kamalsethiya** [comment]
@royclarkson - I cross verified and from features point of view, all the needed things are already implemented related to v2.16. 

We asked this question because in the read me its mentioned that v2.16 is still under development:
![image](https://user-images.githubusercontent.com/2077500/189594936-6c97bb43-2330-435f-922d-58c563d3bc4c.png)

Also, value for constant BrokerApiVersion.API_VERSION_CURRENT is 2.15. Please suggest what's the plan to update its value to 2.16.

**Comment by StefanREbertsch** [comment]
Thank you Ray. We will go forward and see if something else is missing. See the last request from Kamal.

**Comment by royclarkson** [comment]
@kamalsethiya added #358 to update that version in the next release. Thanks.

**Comment by kamalsethiya** [comment]
Thanks @royclarkson.

**Comment by royclarkson** [comment]
All outstanding OSB API 2.16 issues have been addressed
