### ISSUE TITLE
Support 200 and 409 response codes for existing binding requests

### ISSUE THREAD

**Issue by andrejb-dev** [spring-cloud/spring-cloud-open-service-broker#321]
To generate the response in `ServiceInstanceBindingController.createServiceInstanceBinding` this little method is called:

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/a32b84e1836f37b74a40bf1a8262c9c924f63cb8/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceBindingController.java#L144-L155

When the binding existed the method returns 200 OK. But based on [OSB api spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#response-6) (both v2.15 and v2.16), the response should fail with 409 Conflict

409 Conflict | MUST be returned if a Service Binding with the same id, for the same  Service Instance, already exists or is being created but with different  parameters.
-- | --

Maybe I misunderstood that or am I missing something? Thanks.

**Comment by royclarkson** [comment]
Thanks for reporting! I'll review the spec and double check our tests.

**Comment by royclarkson** [comment]
hmm. this is a bit ambiguous. the spec also says a 200 OK `SHOULD be returned if the Service Binding already exists and the requested parameters are identical to the existing Service Binding.`
