### ISSUE TITLE
Release 2.1.3.RELEASE is missing from maven central

### ISSUE THREAD

**Issue by StephenDillon** [spring-cloud/spring-cloud-open-service-broker#324]
Hey,

Not sure the deployment process for this, but we notived 2.1.3.RELEASE never made it to maven central

https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-open-service-broker
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-open-service-broker/2.1.3.RELEASE

**Comment by royclarkson** [comment]
Thanks for reporting. Are you able to use the Spring repo?

https://repo.spring.io/release/org/springframework/cloud/spring-cloud-open-service-broker/2.1.3.RELEASE/

As a side note, that version is built against Spring Boot 2.0. I do recommend that you consider upgrading to a newer version of Spring Cloud Open Service Broker and Spring Boot.

**Comment by StephenDillon** [comment]
I believe we where able to pull it up to a newer version alright, so we should be good here. Thanks!
