### ISSUE TITLE
Spring Boot 2.5.x compatibility

### ISSUE THREAD

**Issue by dennis-menge** [spring-cloud/spring-cloud-open-service-broker#327]
The current state does not support Spring Boot 2.5 due to missing JSON property mappings.

**Comment by royclarkson** [comment]
Thanks for reporting. We'll work on releasing a Boot 2.5 compatible version of SCOSB.

**Comment by royclarkson** [comment]
closed in d9058126c6bb6a7a36903e355fc9c0e61a9017f6

**Comment by royclarkson** [comment]
Commit message should be for Boot 2.5.5 (not 3.5.5). Apologies for the confusion.

**Comment by royclarkson** [comment]
Duplicate of #320  and #330
