### ISSUE TITLE
Upgrade to log4j 2.15.0

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-open-service-broker#338]

**Comment by scottfrederick** [comment]
Does this project use Log4j? I don't see it in any of the `build.gradle` files. 

For the modules that use Spring Boot, Boot doesn't use Log4j by default. It manages a dependency version for Log4J but you won't get a transitive dependency on Log4j from Spring Boot.

**Comment by royclarkson** [comment]
@scottfrederick good point. thanks! No need for us to pin it to a certain version then.
