### ISSUE TITLE
Review and update docs plugin as necessary

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-open-service-broker#373]

**Comment by royclarkson** [comment]
@Buzzardo mind reviewing this project for docs updates as well?

**Comment by Buzzardo** [comment]
I made https://github.com/spring-cloud/spring-cloud-open-service-broker/pull/374 to update the docs. Thanks, Roy. :)

**Comment by royclarkson** [comment]
Closed in #374
