### ISSUE TITLE
Move configuration to a Boot starter subproject

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-open-service-broker#47]
The project currently contains `@Controller` and support classes that implement the service broker API along with Spring Boot configuration in the same library. This ties apps that use the project to Spring Web MVC and limits flexibility (as pointed out in https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/pull/33). 

All configuration code should be re-implemented using Spring Boot auto-configuration and moved to a separate sub-project, leaving the main library to depend only on core Spring Framework.

**Comment by royclarkson** [comment]
@scottfrederick mind reviewing and closing if you agree that this is complete? thanks.
