### ISSUE TITLE
Plans on when version 4.2.0 will be released

### ISSUE THREAD

**Issue by dietzsch** [spring-cloud/spring-cloud-open-service-broker#569]
Hello community,

In the README you mention that the current version 4.1.x is based on Spring Boot 3.1.x and Spring Framework 6.0.x. As support for Spring Boot 3.1.x is running out of support in Q2, is there any schedule/plan, when you will release 4.2.0?

Thank you in advance!

Alex

**Comment by royclarkson** [comment]
@dietzsch thanks for the inquiry and interest in the project. We'll release 4.2.0 soon.

**Comment by dietzsch** [comment]
@royclarkson thanks a lot! Very much appreciated.

**Comment by dietzsch** [comment]
Hi @royclarkson, 

I tried to test the milestone you created for the 4.2.0 release, but I was wondering where are the binaries published? On Maven Central and also Spring Milestone repository I don't see them. The last milestone for 4.1.0 from end of last year I can see on the Spring Milestone repository, but this one is the last artifact published there.
Thanks a lot!

Alex

**Comment by royclarkson** [comment]
@dietzsch ah, that's embarrassing. Thanks for letting us know. I forgot to promote from staging to the milestone repo. It's done now, and you can see it here: https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-open-service-broker/4.2.0-M1/

**Comment by dietzsch** [comment]
@royclarkson great, then we can already start testing with the new version.

**Comment by royclarkson** [comment]
@dietzsch we don't have any more changes to make for 4.2.0, and are planning to push an RC1 and GA releases this week. If you have any feedback over the next few days, please open issues. Outside of dependency updates, the big change in this release is the adoption of the spring-javaformat plugin and the code changes to address violations. Thanks.

**Comment by dietzsch** [comment]
@royclarkson tests were successful and so far we haven't seen any issues.
