### ISSUE TITLE
Author migration guide 

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-open-service-broker#63]
Provide guidance on migrating from `spring-cloud-cloudfoundry-service-broker:1.0.x` to `spring-cloud-open-service-broker:2.0.x`. This could be done in wiki pages in this repo, as is being done with [Spring Boot](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide).

**Comment by royclarkson** [comment]
@scottfrederick does the [migration guide](https://github.com/spring-cloud/spring-cloud-open-service-broker/wiki/2.0-Migration-Guide) complete this?

**Comment by scottfrederick** [comment]
@royclarkson I think so.
