### ISSUE TITLE
Update docs server to use new subproject names and directories

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-open-service-broker#72]
Dependent on #71

**Comment by royclarkson** [comment]
@scottfrederick we're ready for this

**Comment by scottfrederick** [comment]
* Snapshots: https://docs.spring.io/spring-cloud-open-service-broker/docs/2.0.0.BUILD-SNAPSHOT/apidocs/
* M1: https://docs.spring.io/spring-cloud-open-service-broker/docs/2.0.0.M1/apidocs/
