### ISSUE TITLE
Quick Start: Wrong artifact name

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-cloud/spring-cloud-open-service-broker#79]
https://cloud.spring.io/spring-cloud-open-service-broker/

The quick start section has the artifact as "spring-cloud-starter-open-service-broker-webmvc". Was having troubles finding the artifact in the maven repositories. When I came to the repo here I saw that the "starter" in the artifact name was actually later as "spring-cloud-open-service-broker-starter-webmvc". As soon as I changed that the dependency was picked up. Might cause others confusion on first go.

**Comment by scottfrederick** [comment]
@ShawnTuatara Good catch, thanks. 

@royclarkson I thought we'd decided to use `spring-cloud-starter-open-service-broker-web[mvc|flux]` to be consistent with other Spring Cloud projects that use `spring-cloud-starter` as a prefix. Do you remember something different?

**Comment by royclarkson** [comment]
@scottfrederick I remember discussing it :) But I don't remember making a final decision, or it slipped through the cracks. Feel free to change it if you feel strongly about the name.

@ShawnTuatara apologies for the inconvenience!

**Comment by scottfrederick** [comment]
Fixed in 0cf3bc0cab1914f3ade8543ad155dc108afb53d0. 

The project page will be correct for `2.0.0.BUILD-SNAPSHOT`, but will continue to be incorrect for `2.0.0.M2` until we do the next release.
