### ISSUE TITLE
auth failure when doing a create service

### ISSUE THREAD

**Issue by JaredGordon** [spring-cloud/spring-cloud-open-service-broker#80]
Hello, creating a service broker. am able to push and register the broker, but then run into:

Authentication with the service broker failed. Double-check that the username and password are correct

This happens if I use the uid/pw returned by spring security, or if I override via SPRING_SECURITY_USER_NAME and SPRING_SECURITY_USER_PASSWORD env variables. 

Logs just show 401s.

Thanks,

-- Jared

**Comment by scottfrederick** [comment]
Are you configuring the security of the OSB API endpoints in your broker app, as shown [in the docs](https://docs.spring.io/spring-cloud-open-service-broker/docs/2.0.0.M2/reference/html5/#service-broker-security)?  Can you show an example of your security configuration?

**Comment by JaredGordon** [comment]
Hi Scott: the docs! I was going off of the readme in github and just plowing along in true noob fashion. Let me go through these: I'm sure they will help. Thanks.

**Comment by scottfrederick** [comment]
I'll update the README to reference the new docs. There's also a [migration guide](https://github.com/spring-cloud/spring-cloud-open-service-broker/wiki/2.0-Migration-Guide) that we should like to from the README.

**Comment by scottfrederick** [comment]
Addressed via 477365373bb5d903cd4d86c5d4a3c13aa933267c.

**Comment by scottfrederick** [comment]
The OSB API specification does not specify if, or how, service brokers should be secured. It is silent on the topics of authentication and authorization. 

Cloud Foundry requires HTTP basic (username and password) authentication for service broker `/v2` endpoints. Support for OAuth2 as an alternative is planned. 

Kubernetes does not require any authentication for service broker `/v2` endpoints, but supports both HTTP basic and OAuth2.

**Comment by JaredGordon** [comment]
OK, thanks for the info, will continue plugging away at this later this week.

**Comment by JaredGordon** [comment]
I was able to get things working on pcf with a few tweaks to my security config:

`@EnableWebSecurity
@Configuration
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().disable()
                .authorizeRequests()
                .antMatchers("/v2/**").hasRole("ADMIN")
                .antMatchers("/error/**").permitAll()
                .and()
                .httpBasic();
    }

    @Bean
    public InMemoryUserDetailsManager userDetailsService(Environment env) {
        return new InMemoryUserDetailsManager(adminUser(env));
    }

    private UserDetails adminUser(Environment env) {
        return User
                .withUsername(env.getProperty(SqlServerServiceInfo.SPRING_SECURITY_USER_KEY))
                .password("{noop}" + env.getProperty(SqlServerServiceInfo.SPRING_SECURITY_PW_KEY))
                .roles("ADMIN")
                .build();
    }
}`

the tweaks were to add the csrf().disable() to get the broker to stop rejected requests from cloud controller, and the "{noop}" string to the password, or there would be exceptions about a lack of a password encoder. I tried other encoders to no avail.

**Comment by scottfrederick** [comment]
@JaredGordon Sounds like you're on the right path. I'm going to close this issue as it looks like there's nothing to change in this project.
