### ISSUE TITLE
Add support for service instance sharing

### ISSUE THREAD

**Issue by jenspinney** [spring-cloud/spring-cloud-open-service-broker#81]
A new feature allowing service instances to be shared across orgs and spaces was released in cf-deployment version 1.10.0. This doc explains the very simple step required to enable this feature for your service (adding a shareable field to your service-level metadata in the catalog). Have you thought about enabling this for your service?

**Comment by royclarkson** [comment]
The link didn't get included in the issue. However, we provide a [`Map`](https://docs.spring.io/spring-cloud-open-service-broker/docs/current/apidocs/org/springframework/cloud/servicebroker/model/catalog/ServiceDefinition.html#getMetadata--) for the various metadata properties supported on different platforms. I believe this should be sufficient. Let us know if this doesn't cover your use case. Thanks!

**Comment by jenspinney** [comment]
Ah, ok. And thanks for the heads-up on the missing link. I've added it now for completeness.
