### ISSUE TITLE
Incorrect/invalid application.yml causes Spring boot to exit without giving any proper information

### ISSUE THREAD

**Issue by RawSanj** [spring-cloud/spring-cloud-open-service-broker#84]
## Bug report: 

Spring Boot 2.0.X exists without giving any proper error info when `application.yml` is invalid and 
`spring-cloud-open-service-broker-starter-webmvc` is on classpath.

## Sample Application - [boot-open-service-yaml-issue](https://github.com/RawSanj/boot-open-service-yaml-issue)

Logs when running above Application:

	14:43:36.639 [background-preinit] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
	14:43:36.655 [background-preinit] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.9.Final
	14:43:36.655 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
	14:43:36.671 [background-preinit] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
	14:43:36.671 [background-preinit] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
	14:43:36.671 [background-preinit] DEBUG org.hibernate.validator.internal.xml.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
	14:43:36.671 [background-preinit] DEBUG org.hibernate.validator.internal.xml.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
	14:43:36.921 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
	14:43:36.921 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
	14:43:36.921 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
	14:43:36.921 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
	14:43:36.921 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
	14:43:36.937 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.

	Process finished with exit code 1

## Note:
I had raised this issue in Spring Boot before https://github.com/spring-projects/spring-boot/issues/12816 but as per this comment - https://github.com/spring-projects/spring-boot/issues/12816#issuecomment-380064580 the problem is with Spring Cloud Open Service Broker using Commons Logging is causing this.

**Comment by royclarkson** [comment]
@RawSanj thanks for reporting!

**Comment by giner** [comment]
Can this issue be reopen? The problem seems to be there  with the latest buildpack. Today we spend a few hours to find the cause of application crashing on start due to lack of information in logs.
