### ISSUE TITLE
Misleading dependency information in project quick start guide

### ISSUE THREAD

**Issue by georgeharley** [spring-cloud/spring-cloud-open-service-broker#85]
In the quick start guide at https://cloud.spring.io/spring-cloud-open-service-broker/#quick-start the Maven and Gradle compile dependencies are listed as:
* `org.springframework.cloud:spring-cloud-starter-open-service-broker-webmvc:${release}`
* `org.springframework.cloud:spring-cloud-starter-open-service-broker-webflux:${release}`

from the [https://repo.spring.io/libs-milestone](https://repo.spring.io/libs-milestone)  repository. This is incorrect; the actual dependencies appear to be:
* `org.springframework.cloud:spring-cloud-open-service-broker-starter-webmvc:${release}`
* `org.springframework.cloud:spring-cloud-open-service-broker-starter-webflux:${release}`

**Comment by royclarkson** [comment]
Thanks. That is a valid observation! We modified the artifact names after the 2.0.0.M2 release to be more consistent with the nomenclature used in other Spring Cloud projects. The artifacts in the snapshot repo reflect this new name. See #79 for more details. The next milestone release will reflect the name change.
