### ISSUE TITLE
Generic exception handler prevents from using custom exceptions

### ISSUE THREAD

**Issue by ihrigb** [spring-cloud/spring-cloud-open-service-broker#90]
Hi Guys,

I found that the custom exception handler at https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-core/src/main/java/org/springframework/cloud/servicebroker/controller/BaseController.java#L217 prevents from using custom exceptions and handle their outcome (HTTP-Status).

E.g. I would like to enable `@ResponseStatus` at my exceptions and handle that with a custom `@ControllerAdvice`. But exceptions are already being handled within the `BaseController`.

If you agree, this is something that could be adopted, I can contribute some code.

BR,
Benjamin

**Comment by scottfrederick** [comment]
@ihrigb That sounds like a legitimate issue to address. We'd be interested to see a solution that solves the problem for you.

**Comment by scottfrederick** [comment]
Fixed via #96
